- hosts: localhost

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.dotfiles
      tags: ["dotfiles"]
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ["mas"]
    - role: fubarhouse.macdock
      tags: ["dock"]

  vars:
    downloads: /tmp

    mas_installed_apps:
      - { id: 497799835, name: "Xcode" }
      - { id: 899247664, name: "TestFlight" }
      - { id: 747648890, name: "Telegram" }
      - { id: 1176895641, name: "Spark" }
      - { id: 1136220934, name: "Infuse" }

    homebrew_taps:
      - txn2/tap
      - koekeishiya/formulae

    homebrew_inistalled_packages:
      - zoxide
      - neovim
      - fnm
      - fzf
      - tmux
      - htop
      - fastfetch
      - skhd
      - gpg
      - jq
      - go
      - gh
      - httpie
      - pinentry-mac
      - cilium-cli
      - kubernetes-cli
      - kubectx
      - kubefwd
      - python
      - minio-mc
      - elixir
      - wget
      - pgcli
      - redis
      - yt-dlp
      - mtr
      - doctl
      - websocat
      - minicom
      - cloudflared
      - vercel-cli
      - wireguard-tools
      - docker-compose
      - txn2/tap/kubefwd

    homebrew_cask_appdir: /Applications
    homebrew_cask_apps:
      - ghostty
      - yaak
      - utm
      - iina
      - infra
      - aptakube
      - tiles
      - kubecontext
      - zed
      - zen-browser
      - docker
      - spotify
      - obsidian
      - discord@canary
      - visual-studio-code@insiders
      - private-internet-access
      - 1password
      - 1password-cli
      - battery-buddy
      - balenaetcher
      - figma
      - qflipper
      - philips-hue-sync
      - font-intel-one-mono

    dotfiles_repo: git@github.com:dustinrouillard/dotfiles.git
    dotfiles_repo_accept_hostkey: true
    dotfiles_repo_version: mac
    dotfiles_repo_local_destination: ~/Projects/Personal/dotfiles
    dotfiles_files:
      - .zshrc
      - .zshrc.d
      - .gitconfig
      - .profile
      - .jwt
      - .bin
      - .skhdrc
      - .osx
      - .hushlogin
      - .gnupg/gpg-agent.conf
      - .config/ghostty

    default_node_version: "21"
    node_versions:
      - "21"

    node_global_packages:
      - npm-check-updates
      - ts-node
      - pnpm
      - "@cloudflare/wrangler"

    go_packages:
      - github.com/cespare/reflex@latest

    pkg_downloads:
      - url: https://github.com/kcrawford/dockutil/releases/download/3.0.2/dockutil-3.0.2.pkg
        name: dockutil-3.0.2.pkg
        target: /

    dockutil_install_path: /usr/local/bin/dockutil
    dockitems_remove_all: true
    dockitems_enabled:
      - name: Zen Browser
        path: "/Applications/Zen Browser.app"
        pos: 1
      - name: Spotify
        path: "/Applications/Spotify.app"
        pos: 2
      - name: Ghostty
        path: "/Applications/Ghostty.app"
        pos: 3
      - name: Discord Canary
        path: "/Applications/Discord Canary.app"
        pos: 4
      - name: Home
        path: "/Applications/Home.app"
        pos: 5
      - name: Spark
        path: "/Applications/Spark.app"
        pos: 6
      - name: Aptakube
        path: "/Applications/Aptakube.app"
        pos: 7
      - name: Infra
        path: "/Applications/Infra.app"
        pos: 8
      - name: Zed
        path: "/Applications/Zed.app"
        pos: 9
      - name: 1Password
        path: "/Applications/1Password.app"
        pos: 10
      - name: Telegram
        path: "/Applications/Telegram.app"
        pos: 11
      - name: Yaak
        path: "/Applications/Yaak.app"
        pos: 12
      - name: TablePlus
        path: "/Applications/TablePlus.app"
        pos: 13
      - name: System Preferences
        path: "/Applications/System Settings.app"
        pos: 14
      - name: Infuse
        path: "/Applications/Infuse.app"
        pos: 15

    pmset_options:
      - name: displaysleep
        value: 0

    osx_script: "~/.osx"

  tasks:
    - import_tasks: tasks/osx.yml
      tags: ["osx"]
    - import_tasks: tasks/node.yml
      tags: ["node"]
    - import_tasks: tasks/go.yml
      tags: ["go"]
    - import_tasks: tasks/pkg.yml
      tags: ["pkg"]
    - import_tasks: tasks/pmset.yml
      tags: ["pmset"]
