- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    pacman_packages:
      - base-devel

    aur_packages:
      - vlc
      - spotify
      - firefox
      - kitty
      - 1password
      - discord-canary
      - visual-studio-code-insiders-bin

      - go
      - elixir
      - fnm-bin

      - jq
      - yq
      - bat

      - mtr
      - fzf
      - tmux
      - neovim
      - neofetch
      - websocat
      - yt-dlp
      - cloudflared
      - bluez
      - bluez-utils

      - waynergy
      - xorg-xwayland-explicit-sync-git

      - spectacle
      - wl-clipboard

      - htop
      - gtop
      - nvtop

      - docker
      - docker-compose
      - kubectl
      - kubectx
      - kubefwd-bin

      - pgcli
      - redis
      - minio-client

    dotfiles_repo: git@github.com:dustinrouillard/dotfiles.git
    dotfiles_repo_accept_hostkey: true
    dotfiles_repo_version: arch
    dotfiles_repo_local_destination: ~/Projects/Personal/dotfiles
    dotfiles_files:
      - .zshrc
      - .zshrc.d
      - .gitconfig
      - .bin
      - .config/albert.conf
      - .config/albert/websearch/engines.json
      - .config/kitty/kitty.conf
      - .config/waynergy/config.ini
      - .local/share/applications/albert.desktop
      - .local/share/applications/screenshot.desktop
      - .local/share/applications/discord-canary.desktop
      - .local/share/applications/com.obsproject.Studio.desktop
      - .local/share/applications/com.obsproject.Studio-story.desktop
      - .mozilla/firefox/dstn.default/user.js
      - .mozilla/firefox/profiles.ini
      - .hushlogin

    default_node_version: "20"
    node_versions:
      - "20"

    npm_global_packages:
      - pnpm

    pnpm_global_packages:
      - npm-check-updates
      - vercel
      - miniflare
      - ts-node
      - wrangler

    go_packages:
      - github.com/cespare/reflex@latest

    kde_globals:
      main:
        - name: Copy
          keys:
            - Meta+C
            - Ctrl+Ins
            - Ctrl+C
        - name: Cut
          keys:
            - Meta+X
            - Ctrl+X
        - name: Paste
          keys:
            - Meta+V
            - Ctrl+V
        - name: Find
          keys:
            - Meta+F
            - Ctrl+F
        - name: New
          keys:
            - Meta+N
            - Ctrl+N
        - name: Redo
          keys:
            - Meta+Y
            - Ctrl+Shift+Y
            - Ctrl+Shift+Z
        - name: Save
          keys:
            - Meta+S
            - Ctrl+S
        - name: SelectAll
          keys:
            - Meta+A
            - Ctrl+A
        - name: Undo
          keys:
            - Meta+U
            - Ctrl+U
        - name: KeyBindings
          state: unbound
        - name: Preferences
          state: unbound
        - name: WhatsThis
          state: unbound
        - name: Help
          state: unbound
      shortcuts:
        - name: services,org.kde.spectacle.desktop
          keys:
            - name: ActiveWindowScreenShot
            - name: FullScreenScreenShot
            - name: RecordRegion
            - name: RecordScreen
            - name: RecordWindow
            - name: RectangularRegionScreenShot
            - name: WindowUnderCursorScreenShot
            - name: _launch
        - name: plasmashell
          keys:
            - name: next activity
              value: "none,Meta+Tab,Walk through activities"
        - name: plasmashell
          keys:
            - name: previous activity
              value: "none,Meta+Shift+Tab,Walk through activities (Reverse)"
        - name: plasmashell
          keys:
            - name: manage activities
              value: "none,Meta+Q,Show Activity Switcher"
        - name: kaccess
          keys:
            - name: Toggle Screen Reader On and Off
              value: "none,Meta+Alt+S,Toggle Screen Reader On and Off"
        - name: kwin
          keys:
            - name: Walk Through Windows Alternative
              value: "Meta+Tab,,Walk Through Windows Alternative"
        - name: kwin
          keys:
            - name: Walk Through Windows Alternative (Reverse)
              value: "Meta+Shift+Tab,,Walk Through Windows Alternative (Reverse)"

  pre_tasks:
    - import_tasks: tasks/setup-zsh.yml
      tags: ["zsh"]
    - import_tasks: tasks/pre_dotfiles.yml
      tags: ["dotfiles"]

  roles:
    - role: geerlingguy.dotfiles
      tags: ["dotfiles"]

  tasks:
    - import_tasks: tasks/pacman.yml
      tags: ["pacman"]
    - import_tasks: tasks/paru.yml
      tags: ["paru"]
    - import_tasks: tasks/aur.yml
      tags: ["aur"]
    - import_tasks: tasks/node.yml
      tags: ["node"]
    - import_tasks: tasks/go.yml
      tags: ["go"]
    - import_tasks: tasks/bluetooth.yml
      tags: ["bluetooth"]
    - import_tasks: tasks/kde.yml
      tags: ["kde"]
