- hosts: localhost

  roles:
    - role: elliotweiser.osx-command-line-tools
#    - role: geerlingguy.mac.homebrew
#      tags: ["homebrew"]
    - role: geerlingguy.dotfiles
      tags: ["dotfiles"]
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ["mas"]
    - role: fubarhouse.macdock
      tags: ["dock"]

  vars:
    downloads: /tmp

    mas_installed_apps:
      - { id: 497799835, name: "Xcode" }
      - { id: 899247664, name: "TestFlight" }
      - { id: 747648890, name: "Telegram" }
      - { id: 1176895641, name: "Spark" }
      - { id: 1136220934, name: "Infuse" }

    homebrew_taps:
      - txn2/tap
      - koekeishiya/formulae
      - productdevbook/tap

    x_homebrew_installed_packages:
      - zoxide
      - neovim
      - fnm
      - fzf
      - tmux
      - htop
      - fastfetch
      - asmvik/formulae/skhd
      - gpg
      - jq
      - go
      - gh
      - httpie
      - pinentry-mac
      - cilium-cli
      - kubernetes-cli
      - kubectx
      - kubefwd
      - python
      - minio-mc
      - elixir
      - wget
      - pgcli
      - redis
      - yt-dlp
      - mtr
      - doctl
      - websocat
      - minicom
      - cloudflared
      - vercel-cli
      - wireguard-tools
      - docker
      - docker-compose
      - txn2/tap/kubefwd
      - helmfile
      - sops
      - age

    homebrew_cask_appdir: /Applications
    x_homebrew_cask_apps:
      - obs
      - jordanbaird-ice
      - ghostty
      - yaak
      - utm
      - iina
      - aptakube
      - tiles
      - kubecontext
      - zed
      - zed@preview
      - firefox@nightly
      - spotify
      - obsidian
      - discord@canary
      - discord@ptb
      - 1password@nightly
      - 1password-cli
      - battery-buddy # TOOD: Make this not install on the mac mini
      - balenaetcher
      - figma
      - qflipper
      - font-intel-one-mono
      - portkiller
      - claude
      - claude-code@latest
      - chatgpt
      - codex
      - codexbar

    dotfiles_repo: git@github.com:dustinrouillard/dotfiles.git
    dotfiles_repo_accept_hostkey: true
    dotfiles_repo_version: mac
    dotfiles_repo_local_destination: ~/Projects/Personal/dotfiles
    dotfiles_files:
      - .zshrc
      - .zshrc.d
      - .gitconfig
      - .profile
      - .jwt
      - .bin
      - .skhdrc
      - .osx
      - .hushlogin
      - .gnupg/gpg-agent.conf
      - .config/ghostty

    default_node_version: "26"
    node_versions:
      - "26"

    node_global_packages:
      - npm-check-updates
      - ts-node
      - pnpm

    go_packages:
      - github.com/cespare/reflex@latest

    ## TODO: Use our own local repository for dockutil, as I refuse to update something that works fine :)
    pkg_downloads:
      - url: https://github.com/kcrawford/dockutil/releases/download/3.0.2/dockutil-3.0.2.pkg
        name: dockutil-3.0.2.pkg
        target: /

    dockutil_install_path: /usr/local/bin/dockutil
    dockitems_remove_all: true
    dockitems_enabled:
      - name: Spotify
        path: "/Applications/Spotify.app"
        pos: 1
      - name: Ghostty
        path: "/Applications/Ghostty.app"
        pos: 2
      - name: Discord Canary
        path: "/Applications/Discord Canary.app"
        pos: 3
      - name: Home
        path: "/Applications/Home.app"
        pos: 4
      - name: Home Assistant
        path: "/Users/dustin/Applications/Home Assistant.app"
        pos: 5
      - name: Frigate
        path: "/Users/dustin/Applications/Frigate.app"
        pos: 6
      - name: Spark
        path: "/Applications/Spark.app"
        pos: 7
      - name: Obsidian
        path: "/Applications/Obsidian.app"
        pos: 8
      - name: Aptakube
        path: "/Applications/Aptakube.app"
        pos: 9
      - name: Firefox Nightly
        path: "/Applications/Firefox Nightly.app"
        pos: 10
      - name: Zed Preview
        path: "/Applications/Zed Preview.app"
        pos: 11
      - name: 1Password
        path: "/Applications/1Password.app"
        pos: 12
      - name: Telegram
        path: "/Applications/Telegram.app"
        pos: 13
      - name: Claude
        path: "/Applications/Claude.app"
        pos: 14
      - name: ChatGPT
        path: "/Applications/ChatGPT.app"
        pos: 15
      - name: Yaak
        path: "/Applications/Yaak.app"
        pos: 16
      - name: TablePlus
        path: "/Applications/TablePlus.app"
        pos: 17
      - name: System Preferences
        path: "/Applications/System Settings.app"
        pos: 18
      - name: Infuse
        path: "/Applications/Infuse.app"
        pos: 19
      - name: Screen Sharing
        path: "/System/Applications/Utilities/Screen Sharing.app"
        pos: 20

    pmset_options:
      - name: displaysleep
        value: 0

    osx_script: "~/.osx"

  tasks:
    - name: Brew - Temporary
      ansible.builtin.import_tasks: tasks/brew.yml
      tags: ["homebrew"]
    - import_tasks: tasks/osx.yml
      tags: ["osx"]
    - import_tasks: tasks/node.yml
      tags: ["node"]
    - import_tasks: tasks/go.yml
      tags: ["go"]
    - import_tasks: tasks/pkg.yml
      tags: ["pkg"]
    - import_tasks: tasks/pmset.yml
      tags: ["pmset"]
