- hosts: localhost

  vars:
    pacman_packages:
      - base-devel

    aur_packages:
      - spotify
      - firefox
      - kitty
      - 1password
      - discord-canary
      - visual-studio-code-insiders-bin

      - go
      - elixir
      - fnm-bin

      - jq
      - yq

      - mtr
      - fzf
      - tmux
      - neovim
      - neofetch
      - xbindkeys
      - websocat
      - docker
      - yt-dlp
      - cloudflared

      - htop
      - gtop
      - nvtop

      - kubectl
      - kubectx
      - kubefwd-bin

      - pgcli
      - redis
      - minio-client

    dotfiles_repo: git@github.com:dustinrouillard/dotfiles.git
    dotfiles_repo_accept_hostkey: true
    dotfiles_repo_version: arch
    dotfiles_repo_local_destination: ~/Projects/Personal/dotfiles
    dotfiles_files:
      - .zshrc
      - .zsh_funcs
      - .zsh_alias
      - .gitconfig
      - .bin
      - .config/kitty/kitty.conf
      - .local/share/applications/firefox.desktop
      - .local/share/applications/com.obsproject.Studio.desktop
      - .local/share/applications/com.obsproject.Studio-story.desktop
      - .mozilla/firefox/dstn.default/user.js
      - .xbindkeysrc
      - .hushlogin

    default_node_version: "20"
    node_versions:
      - "20"

    npm_global_packages:
      - pnpm

    pnpm_global_packages:
      - npm-check-updates
      - vercel
      - miniflare
      - ts-node
      - wrangler

    go_packages:
      - github.com/cespare/reflex@latest

  pre_tasks:
    - import_tasks: tasks/pre_dotfiles.yml
      tags: ["dotfiles"]

  roles:
    - role: geerlingguy.dotfiles
      tags: ["dotfiles"]

  tasks:
    - import_tasks: tasks/pacman.yml
      tags: ["pacman"]
    - import_tasks: tasks/paru.yml
      tags: ["paru"]
    - import_tasks: tasks/aur.yml
      tags: ["aur"]
    - import_tasks: tasks/node.yml
      tags: ["node"]
    - import_tasks: tasks/go.yml
      tags: ["go"]
