---
- name: Install node via fnm
  shell:
    cmd: |
      set -o pipefail
      eval "$(fnm env)"
      fnm install {{ item }}
    executable: /bin/bash
  with_items: "{{ node_versions }}"

- name: Set default node version with fnm
  shell:
    cmd: |
      set -o pipefail
      eval "$(fnm env)"
      fnm use {{ default_node_version }} > /dev/null 2>&1
      readlink -f $(command -v node) | sed  -E "s%/node$%%g"
    executable: /bin/bash

- name: Install global npm packages
  shell:
    cmd: |
      set -o pipefail
      source ~/.zshrc
      npm install -g {{ item }} > /dev/null 2>&1
    executable: /bin/zsh
  with_items: "{{ npm_global_packages }}"

- name: Install global pnpm packages
  shell:
    cmd: |
      set -o pipefail
      source ~/.zshrc
      pnpm install -g {{ item }}
    executable: /bin/zsh
  with_items: "{{ pnpm_global_packages }}"
