---
- name: Ensure the proper repositories are enabled
  become: true
  ansible.builtin.copy:
    src: files/pacman.conf
    dest: /etc/pacman.conf
    mode: 0644

- name: Ensure configured aur packages are installed.
  community.general.pacman:
    name: "{{ item.name | default(item) }}"
  become: true
  loop: "{{ pacman_packages }}"
